# Generated by Django 4.0.6 on 2022-07-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_expense_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='amount',
        ),
    ]
